version: '3.4'

services:
  devup.api:
    image: ${DOCKER_REGISTRY-}devupapi
    restart: always
    ports:
        - 5000:80
    build:
      context: .
      dockerfile: DevUp.Api/Dockerfile
    environment:
      JWT_SECRET: 2r5u8x/A?D(G-KaPdSgVkYp3s6v9y$B&
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: pass

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
