version: '3.4'

services:
  devup.api:
    image: ${DOCKER_REGISTRY-}devupapi
    restart: always
    ports:
        - 5000:80
    build:
      context: .
      dockerfile: src/DevUp.Api/Dockerfile
    depends_on:
      - postgres
      - elasticsearch

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./devops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./devops/grafana/datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./devops/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/all.yaml
      - ./devops/grafana/config.ini:/etc/grafana/config.ini
      - ./devops/grafana/dashboards/:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  elasticsearch:
    image: elasticsearch:8.5.2
    restart: always
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data


volumes:
  prometheus_data: {}
  elasticsearch_data: {}