version: '3.8'

services:

  mongo:
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
    depends_on:
      - mongo

  devup.api:
    image: ${DOCKER_REGISTRY-}devupapi
    restart: always
    ports:
      - 5000:80
    env_file: .env
    build:
      context: .
      dockerfile: DevUp.Api/Dockerfile
    depends_on:
      - mongo