version: '3.4'

services:
  devup.api:
    image: ${DOCKER_REGISTRY-}devupapi
    restart: always
    ports:
        - 5000:80
        - 5001:443
    build:
      context: .
      dockerfile: src/DevUp.Api/Dockerfile
    depends_on:
      - postgres

  devup.api.minimal:
    image: ${DOCKER_REGISTRY-}devupapiminimal
    restart: always
    ports:
        - 6000:80
        - 6001:443
    build:
      context: .
      dockerfile: src/DevUp.Api.Minimal/Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
