global:
  scrape_interval: 5s
  scrape_timeout: 3s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
        - host.docker.internal:9090

  - job_name: devupapi
    metrics_path: /metrics
    static_configs:
      - targets:
        - host.docker.internal:5000
    tls_config:
      insecure_skip_verify: true
