apiVersion: 1

datasources:
  - name: 'prometheus'
    type: 'prometheus'
    access: 'proxy'
    url: 'http://prometheus:9090'

  - name: 'devupapi'
    type: 'prometheus'
    access: 'proxy'
    url: 'http://prometheus:9090'