name: Publish nuget

on:
  workflow_run:
    workflows: ["Build and test backend"]
    branches: [ "master", "feature/create-sdk" ]
    types: [ "completed" ]

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-run-wait@v1
      - name: Pack package
        run: dotnet nuget pack DevUp.sln
      - name: Push package to GitHub.com
        run: dotnet nuget push --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/abaniuszewicz/index.json *.nupkg